name: Import tag from external-secrets repo

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter the tag from the external-secrets repo, such as 0.16.1'
        required: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  ESO_TAG: ${{ inputs.tag }}

jobs:
  repo_setup:
    if: ${{ inputs.tag != 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persistent-credentials: true

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create a new branch and remove the external-secrets directory
        run: |
          git checkout -b $ESO_TAG
          git rm -rf external-secrets

      - name: Download external-secrets version package and unpack
        run: |
          curl -sSL -o external-secrets.tgz https://github.com/external-secrets/external-secrets/releases/download/helm-chart-${ESO_TAG}/external-secrets-${ESO_TAG}.tgz
          tar xzvf external-secrets.tgz
          rm external-secrets.tgz

      - name: Apply all changes
        run: |
          git add -A
          git commit -a -m "Adding tag $ESO_TAG"
          git push origin $ESO_TAG

