name: Import tag from external-secrets repo

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter the tag from the external-secrets repo, such as 0.16.1'
        required: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  ESO_TAG: ${{ inputs.tag }}

jobs:
  repo_setup:
    if: ${{ inputs.tag != 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # Check out the external-secrets git repo using the provided version tag
      # ----------------------------------------------------------------------
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create a new branch and remove the external-secrets directory.  Fail if branch already exists.
        run: |
          git checkout -b $ESO_TAG
          if [ -d external-secrets ]; then git rm -rf external-secrets; fi

      - name: Download external-secrets version package and unpack
        run: |
          curl -sSL -o external-secrets.tgz https://github.com/external-secrets/external-secrets/releases/download/helm-chart-${ESO_TAG}/external-secrets-${ESO_TAG}.tgz
          tar xzvf external-secrets.tgz
          rm external-secrets.tgz

      - name: Apply git repo changes
        run: |
          git add -A
          git commit -a -m "Adding tag $ESO_TAG"
          git push origin $ESO_TAG

      # Pull the related image and put it in Artifactory
      # ------------------------------------------------
      - name: Log in to Artifactory
        run: |
          echo "${{ secrets.ARTIFACTORY_PASSWORD }}" | docker login "https://${{ secrets.ARTIFACTORY_URL }}" -u ${{ secrets.ARTIFACTORY_USERNAME }} --password-stdin

      - name: Pull the operator image from oci.external-secrets.io
        run: docker pull --arch amd64 oci.external-secrets.io/external-secrets/external-secrets:v${ESO_TAG}

      - name: Tag image for Artifactory
        run: docker tag oci.external-secrets.io/external-secrets/external-secrets:v${ESO_TAG} ${{ secrets.ARTIFACTORY_URL }}/plat-util-images/external-secrets:v${ESO_TAG}

      - name: Push image to Artifactory
        run: docker push ${{ secrets.ARTIFACTORY_URL }}/plat-util-images/external-secrets:v${ESO_TAG}

